In [2]:
from auxiliary import *
grocery_chain = 'Target'

In [12]:
#Creating a Selenium WebDriver
driver = create_driver(downloads_directory, r'https://www.target.com')

In [9]:
#Zipcodes or Cities to loop over for a store
cities_list = [i for i in top_cities(top=5) if i.rsplit(',')[1]=='ny']

#Creating empty lists
store_name = list()
store_address = list()
store_city = list()
store_state = list()
store_zip = list()
not_found = list()

In [31]:
for specific_city in [cities_list[0]]:
    print(specific_city)
    #Just change the value of these two variables per website
    try:
        driver.get('https://www.target.com/store-locator/find-stores/' + specific_city)
        time.sleep(wait_time*1.5)
        
        #Just change the value of these variables as desired per website
        store_elements = list()
        for element in driver.find_elements_by_class_name('h-padding-b-default'):
            store_elements.append(element)

        '''
        In this part, we need to change the string regular expressions per website
        '''
        for i in store_elements:
            specific_store = i.text.split('\n')
            try:
                store_name.append(specific_store[0].replace('\n',' ').strip())
                print(specific_store[0].replace('\n',' ').strip())
            except:
                store_name.append(None)

            try:
                store_address.append(specific_store[1].rsplit(',',2)[0].replace('\n',' ').strip())
            except:
                store_address.append(None)

            try:
                store_city.append(specific_store[1].rsplit(',',2)[1].replace('\n',' ').strip())
            except:
                store_city.append(None)

            try:
                store_state.append(specific_store[1].rsplit(',',2)[2].strip().split(' ',1)[0].replace('\n',' ').strip())
            except:
                store_state.append(None)

            try:
                store_zip.append(specific_store[1].rsplit(',',2)[2].strip().split(' ',1)[1].replace('\n',' ').strip())
            except:
                store_zip.append(None)
    except:
        not_found.append(specific_city)

new%20york,ny
Tribeca
Lower East Side Grand and Clinton
Manhattan East Village
Jersey City
Brooklyn Fulton St
Atlantic Terminal
Manhattan Herald Square
North Bergen Commons
Brooklyn Junction
Brooklyn Bensonhurst
Harlem
Edgewater
Queens Place
Brooklyn Midwood
Gateway
Forest Hills
Bronx Terminal
Flushing
Clifton
College Point

In [32]:
store_name

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Tribeca',
 'Lower East Side Grand and Clinton',
 'Manhattan East Village',
 'Jersey City',
 'Brooklyn Fulton St',
 'Atlantic Terminal',
 'Manhattan Herald Square',
 'North Bergen Commons',
 'Brooklyn Junction',
 'Brooklyn Bensonhurst',
 'Harlem',
 'Edgewater',
 'Queens Place',
 'Brooklyn Midwood',
 'Gateway',
 'Forest Hills',
 'Bronx Terminal',
 'Flushing',
 'Clifton',
 'College Point',
 'Tribeca',
 'Lower East Side Grand and Clinton',
 'Manhattan East Village',
 'Jersey City',
 'Brooklyn Fulton St',
 'Atlantic Terminal',
 'Manhattan Herald Square',
 'North Bergen Commons',
 'Brooklyn Junction',
 'Brooklyn Bensonhurst',
 'Harlem',
 'Edgewater',
 'Queens Place',
 'Brooklyn Midwood',
 'Gateway',
 'Forest Hills',
 'Bronx Terminal',
 'Flushing',
 'Clifton',
 'College Point']

In [20]:
for cnt,element in enumerate([driver.find_elements_by_class_name('h-padding-b-default')[0]]):
    store_element = element

In [22]:
store_element.text.split('\n')

['Tribeca',
 '255 Greenwich St, New York, NY 10007-2377',
 'open today: 7:00 am - 11:00 pm',
 '(917) 438-2214',
 'store infomake it my store']

In [29]:
#Dataframe creation phase
data = [store_name, store_address, store_city, store_state, store_zip]
df = pd.DataFrame(data)
df = df.transpose()
df.columns = ['Name','Address', 'City', 'State', 'ZIP']

In [30]:
df

,Name,Address,City,State,ZIP
0,None,None,None,None,None
1,None,None,None,None,None
2,None,None,None,None,None
3,None,None,None,None,None
4,None,None,None,None,None
5,None,None,None,None,None
6,None,None,None,None,None
7,None,None,None,None,None
8,None,None,None,None,None
9,None,None,None,None,None
10,None,None,None,None,None
11,None,None,None,None,None
12,None,None,None,None,None
13,None,None,None,None,None
14,None,None,None,None,None
15,None,None,None,None,None
16,None,None,None,None,None
17,None,None,None,None,None
18,None,None,None,None,None
19,None,None,None,None,None
20,None,None,None,None,None
21,None,None,None,None,None
22,None,None,None,None,None
23,None,None,None,None,None
24,None,None,None,None,None
25,None,None,None,None,None
26,None,None,None,None,None
27,None,None,None,None,None
28,None,None,None,None,None
29,None,None,None,None,None
...,...,...,...,...,...
50,None,None,None,None,None
51,None,None,None,None,None
52,None,None,None,None,None
53,None,None,None,None,None
54,None,None,None,None,None
55,None,None,None,None,None
56,None,None,None,None,None
57,None,None,None,None,None
58,None,None,None,None,None
59,None,None,None,None,None
60,Tribeca,255 Greenwich St,New York,NY,10007-2377
61,Lower East Side Grand and Clinton,400 Grand St,New York,NY,10002-3949
62,Manhattan East Village,500 E 14th St,New York,NY,10009
63,Jersey City,100 14th St,Jersey City,NJ,07310-1202
64,Brooklyn Fulton St,445 Albee Square West,BROOKLYN,NY,11201-3016
65,Atlantic Terminal,139 Flatbush Ave,Brooklyn,NY,11217-1403
66,Manhattan Herald Square,112 W 34th St,New York,NY,10120-0101
67,North Bergen Commons,7101 Tonnelle Ave,North Bergen,NJ,07047-4507
68,Brooklyn Junction,1598 Flatbush Ave,Brooklyn,NY,11210-3036
69,Brooklyn Bensonhurst,6401 18th Ave,Brooklyn,NY,11204-3730
70,Harlem,517 E 117th Street,New York,NY,10035-4410
71,Edgewater,543 River Rd,Edgewater,NJ,07020-1146
72,Queens Place,8801 Queens Blvd,Elmhurst,NY,11373-4449
73,Brooklyn Midwood,1715 E. 13th St,Brooklyn,NY,11229-2086
74,Gateway,519 Gateway Dr,Brooklyn,NY,11239-2801
75,Forest Hills,7000 AUSTIN ST,FOREST HILLS,NY,11375-1022
76,Bronx Terminal,700 Exterior St,Bronx,NY,10451-2022
77,Flushing,4024 College Point Blvd,Flushing,NY,11354-5112
78,Clifton,30 Kingsland Rd,Clifton,NJ,07014-1904
79,College Point,13505 20th Ave,College Point,NY,11356-2446

In [ ]:

df.drop_duplicates().to_excel(downloads_directory + '//' + grocery_chain + '.xlsx', index = False)
pd.DataFrame(not_found).to_csv(downloads_directory + '//' + grocery_chain + '_not_found.csv', index = False)

print('Scraping Done')